package MealForms;

import Classes.Meal;
import Classes.MealType;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JToggleButton;

public class ViewMenu extends javax.swing.JFrame {


    ArrayList<Meal> meals = new ArrayList<>();
    ArrayList<MealType> mealType = new ArrayList<>();
    ArrayList<Meal> nonalcoholic = new ArrayList<>();
    ArrayList<Meal> alcoholic = new ArrayList<>();
    ArrayList<Meal> starters = new ArrayList<>();
    ArrayList<Meal> mains = new ArrayList<>();
    ArrayList<Meal> desserts = new ArrayList<>();
    ArrayList<Meal> snacks = new ArrayList<>();
    DefaultListModel lstMealModel = new DefaultListModel();
    ArrayList<JToggleButton> removeButtons = new ArrayList<>();
    int lastButton = 1;
        
    public ViewMenu() {
        initComponents();
        setupForm();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNonAlcohol = new javax.swing.JButton();
        btnAlcohol = new javax.swing.JButton();
        btnStarters = new javax.swing.JButton();
        btnMains = new javax.swing.JButton();
        btnDesserts = new javax.swing.JButton();
        btnSnacks = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        scrPane = new javax.swing.JScrollPane();
        btnRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Menu");

        btnNonAlcohol.setText("Non Alcoholic Drinks");
        btnNonAlcohol.setToolTipText("");
        btnNonAlcohol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNonAlcoholActionPerformed(evt);
            }
        });

        btnAlcohol.setText("Alcoholic Drinks");
        btnAlcohol.setToolTipText("");
        btnAlcohol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlcoholActionPerformed(evt);
            }
        });

        btnStarters.setText("Starters");
        btnStarters.setToolTipText("");
        btnStarters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartersActionPerformed(evt);
            }
        });

        btnMains.setText("Mains");
        btnMains.setToolTipText("");
        btnMains.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainsActionPerformed(evt);
            }
        });

        btnDesserts.setText("Desserts");
        btnDesserts.setToolTipText("");
        btnDesserts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDessertsActionPerformed(evt);
            }
        });

        btnSnacks.setText("Snacks");
        btnSnacks.setToolTipText("");
        btnSnacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSnacksActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        scrPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        btnRemove.setText("Confirm Removals");
        btnRemove.setToolTipText("");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(btnNonAlcohol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlcohol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStarters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMains, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDesserts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSnacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(scrPane, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNonAlcohol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlcohol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnStarters, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMains, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDesserts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSnacks, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrPane))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        
        for (JToggleButton button : removeButtons) {
            meals.remove(removeButtons.indexOf(button));
        }
        
        switch (lastButton) {
            case 1:
                populatePage(nonalcoholic);
                break;
            case 2:
                populatePage(alcoholic);
                break;
            case 3:
                populatePage(starters);
                break;
            case 4:
                populatePage(mains);
                break;
            case 5:
                populatePage(desserts);
                break;
            case 6:
                populatePage(snacks);
                break;
        }
        
        
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnNonAlcoholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNonAlcoholActionPerformed
        lastButton = 1;
        populatePage(nonalcoholic);
    }//GEN-LAST:event_btnNonAlcoholActionPerformed

    private void btnAlcoholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlcoholActionPerformed
        lastButton = 2;
        populatePage(alcoholic);
    }//GEN-LAST:event_btnAlcoholActionPerformed

    private void btnStartersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartersActionPerformed
        lastButton = 3;
        populatePage(starters);
    }//GEN-LAST:event_btnStartersActionPerformed

    private void btnMainsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainsActionPerformed
        lastButton = 4;
        populatePage(mains);
    }//GEN-LAST:event_btnMainsActionPerformed

    private void btnDessertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDessertsActionPerformed
        lastButton = 5;
        populatePage(desserts);
    }//GEN-LAST:event_btnDessertsActionPerformed

    private void btnSnacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSnacksActionPerformed
        lastButton = 6;
        populatePage(snacks);
    }//GEN-LAST:event_btnSnacksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenu().setVisible(true);
            }
        });
    }
    
    public void setupForm() {
        meals = Utilities.IntergratedProjectStaffApplication.JSPConnector.getAllMeal();        
        sortLists();
        populatePage(nonalcoholic);
    }
    
    public void sortLists() {   
        
        nonalcoholic.clear();
        alcoholic.clear();
        starters.clear();
        mains.clear();
        desserts.clear();
        snacks.clear();
        
        for (Meal meal : meals) {
            switch (meal.getMealTypeID()) {
                case 1:
                    nonalcoholic.add(meal);
                    break;
                case 2:
                    alcoholic.add(meal);
                    break;
                case 3:
                    starters.add(meal);
                    break;
                case 4:
                    mains.add(meal);
                    break;
                case 5:
                    desserts.add(meal);
                    break;
                case 6:
                    snacks.add(meal);
                    break;
            }
        }        
    }
    
    public void populatePage(ArrayList<Meal> mealList) {
        
        scrPane.removeAll();
        
        for (int i = 0; i < mealList.size(); i++) {
            
            JPanel panel = new JPanel();
            panel.setSize(615, 200);
            
            JLabel mealTitle = new JLabel();
            mealTitle.setText( mealList.get(i).getName() + "     " + mealList.get(i).getPrice());
            mealTitle.setVisible(true);
            panel.add(mealTitle);
            
            JLabel mealDescription = new JLabel();
            mealDescription.setText(mealList.get(i).getDescription());
            mealDescription.setVisible(true);
            panel.add(mealDescription);
            
            JToggleButton button = new JToggleButton();
            button.setText("Remove");
            button.setVisible(true);
            panel.add(button);            
            
            panel.setVisible(true);
            scrPane.getViewport().add(panel);            
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlcohol;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDesserts;
    private javax.swing.JButton btnMains;
    private javax.swing.JButton btnNonAlcohol;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSnacks;
    private javax.swing.JButton btnStarters;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scrPane;
    // End of variables declaration//GEN-END:variables
}
