package StaffForms;

import Classes.Staff;
import Utilities.IntergratedProjectStaffApplication;
import UtilityForms.EmailForm;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


public class ViewEditStaff extends javax.swing.JFrame {
    
    
    ArrayList<String> lstStaffModel;
    ArrayList<Staff> originalStaff = new ArrayList<>();
    ArrayList<Staff> searchedStaff = new ArrayList<>();
    Staff currentStaff;
    Boolean searchActivated = false;
    int selectedRad = 2;
    int currentSelection = 0;

    public ViewEditStaff() {
        initComponents();
        formSetup(); //set up form
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSearchFirstName = new javax.swing.JTextField();
        txtSearchSurname = new javax.swing.JTextField();
        radStaff = new javax.swing.JRadioButton();
        radManagement = new javax.swing.JRadioButton();
        radBoth = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstStaff = new javax.swing.JList<>();
        txtSurname = new javax.swing.JTextField();
        txtPhoneNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbManager = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnEmailStaff = new javax.swing.JButton();
        btnEmailAllStaff = new javax.swing.JButton();
        btnAddStaff = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        jLabel5.setText("First Name :");

        jCheckBox1.setText("Manager");

        jLabel6.setText("Surname :");

        jLabel7.setText("Phone Number :");

        jLabel8.setText("Email :");

        jLabel9.setText("Password :");

        jLabel10.setText("Management :");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Search Staff");

        jLabel2.setText("First Name :");

        jLabel3.setText("Surname :");

        jLabel4.setText("Staff Management :");

        buttonGroup1.add(radStaff);
        radStaff.setText("Staff");
        radStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radStaffActionPerformed(evt);
            }
        });

        buttonGroup1.add(radManagement);
        radManagement.setText("Management");
        radManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radManagementActionPerformed(evt);
            }
        });

        buttonGroup1.add(radBoth);
        radBoth.setSelected(true);
        radBoth.setText("both");
        radBoth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBothActionPerformed(evt);
            }
        });

        lstStaff.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstStaff);

        jLabel11.setText("First Name :");

        cbManager.setText("Manager");

        jLabel12.setText("Surname :");

        jLabel13.setText("Phone Number :");

        jLabel14.setText("Email :");

        jLabel16.setText("Management :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("Staff Details");

        btnConfirm.setText("Confirm");
        btnConfirm.setPreferredSize(new java.awt.Dimension(125, 40));
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnChangePassword.setText("Change Password");
        btnChangePassword.setPreferredSize(new java.awt.Dimension(125, 40));
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        btnEmailStaff.setText("Email Staff");
        btnEmailStaff.setPreferredSize(new java.awt.Dimension(125, 40));
        btnEmailStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmailStaffActionPerformed(evt);
            }
        });

        btnEmailAllStaff.setText("Email All Staff");
        btnEmailAllStaff.setPreferredSize(new java.awt.Dimension(125, 40));
        btnEmailAllStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmailAllStaffActionPerformed(evt);
            }
        });

        btnAddStaff.setText("Add Staff");
        btnAddStaff.setPreferredSize(new java.awt.Dimension(125, 40));
        btnAddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStaffActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove Staff");
        btnRemove.setPreferredSize(new java.awt.Dimension(125, 40));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFirstName)
                                    .addComponent(txtSurname)
                                    .addComponent(cbManager)
                                    .addComponent(txtEmail)
                                    .addComponent(txtPhoneNo)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEmailAllStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEmailStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearchFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearchSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radStaff)
                        .addGap(18, 18, 18)
                        .addComponent(radManagement)
                        .addGap(18, 18, 18)
                        .addComponent(radBoth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearchFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtSearchSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(radStaff)
                    .addComponent(radManagement)
                    .addComponent(radBoth)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cbManager))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEmailStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEmailAllStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        
        boolean validation;
        
        validation = Utilities.Utilities.nullCheck(txtFirstName, "First name", "First Name") && Utilities.Utilities.alphbetic(txtFirstName.getText(), "First Name", "First Name") &&
                Utilities.Utilities.nullCheck(txtSurname, "Surname", "Surname") && Utilities.Utilities.alphanumeric(txtSurname.getText(), "Surname", "Surname") &&
                Utilities.Utilities.nullCheck(txtEmail, "Email", "Email") && Utilities.Utilities.emailCheck(txtEmail) &&
                Utilities.Utilities.nullCheck(txtPhoneNo, "Phone number", "Phone Number") && Utilities.Utilities.phoneNoCheck(txtPhoneNo.getText());
        
        if (validation) {
            setCurrentStaff(); //update details
            IntergratedProjectStaffApplication.JSPConnector.updateStaff(currentStaff);
            
            searchActivated = true;
            listLoad();
            lstStaff.setSelectedIndex(currentSelection);
            
            Utilities.Utilities.infoBox( currentStaff.getFirstName() + " " + currentStaff.getSurname() + " Updated", "Staff Updated" );
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        searchActivated = true;
        
        //clear search array for results
        searchedStaff.clear();
        
        //get search values
        String searchFirstName = txtSearchFirstName.getText();
        String searchSurname = txtSearchSurname.getText();
        
        //search
        if (!searchFirstName.isEmpty() && !searchSurname.isEmpty() && selectedRad == 2) {    //search both boxs all staff        
            for (Staff staff : originalStaff) {
                if (staff.getFirstName().equalsIgnoreCase(searchFirstName) && staff.getSurname().equalsIgnoreCase(searchSurname)) {
                    searchedStaff.add(staff);
                }
            }
        } else if (!searchFirstName.isEmpty() && !searchSurname.isEmpty() && selectedRad != 2) { //search both boxs half staff
            for (Staff staff : originalStaff) {
                if (staff.getFirstName().equalsIgnoreCase(searchFirstName) && staff.getSurname().equalsIgnoreCase(searchSurname) && staff.getManager() == selectedRad) {
                    searchedStaff.add(staff);
                }
            }
        } else if (!searchFirstName.isEmpty() && selectedRad == 2) { //search first name only all staff
            for (Staff staff : originalStaff) {
                if (staff.getFirstName().equalsIgnoreCase(searchFirstName)) {
                    searchedStaff.add(staff);
                }
            }
        } else if (!searchFirstName.isEmpty() && selectedRad != 2) { //search first name only half staff
            for (Staff staff : originalStaff) {
                if (staff.getFirstName().equalsIgnoreCase(searchFirstName) && staff.getManager() == selectedRad) {
                    searchedStaff.add(staff);
                }
            }
        } else if (!searchSurname.isEmpty() && selectedRad == 2) { //search surname only all staff            
            for (Staff staff : originalStaff) {
                if (staff.getSurname().equalsIgnoreCase(searchSurname)) {
                    searchedStaff.add(staff);
                }
            }
        } else if (!searchSurname.isEmpty() && selectedRad != 2) { //search surname only half staff
            for (Staff staff : originalStaff) {
                if (staff.getSurname().equalsIgnoreCase(searchSurname) && staff.getManager() == selectedRad) {
                    searchedStaff.add(staff);
                }
            }
        }
        
        //display message for no results
        if (searchedStaff.isEmpty()) {
            for (Staff staff : originalStaff) {
                searchedStaff.add(staff);
            }
            txtSearchFirstName.setText("");
            txtSearchSurname.setText("");
            Utilities.Utilities.infoBox("No matching results - Resetting List", "Search results");
        }
        listLoad();
        lstStaff.setSelectedIndex(0);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void radStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radStaffActionPerformed
        selectedRad = 0;
    }//GEN-LAST:event_radStaffActionPerformed

    private void radManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radManagementActionPerformed
        selectedRad = 1;
    }//GEN-LAST:event_radManagementActionPerformed

    private void radBothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBothActionPerformed
        selectedRad = 2;
    }//GEN-LAST:event_radBothActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you wish to remove " + currentStaff.getFirstName() + " " + currentStaff.getSurname(),"Remove Staff", JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            
            IntergratedProjectStaffApplication.JSPConnector.deleteStaff(currentStaff);
            
            originalStaff.remove(currentStaff);
            searchedStaff.remove(currentStaff);            
            
            searchActivated = true;
            listLoad();            
            Utilities.Utilities.infoBox("Staff removed : " + currentStaff.getFirstName() + " " + currentStaff.getSurname() , "Staff Removed");
            lstStaff.setSelectedIndex(0);
            }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        if (Utilities.IntergratedProjectStaffApplication.changePassword != null) {
            Utilities.IntergratedProjectStaffApplication.changePassword.dispose();
        }
        Utilities.IntergratedProjectStaffApplication.changePassword = new ChangePassword(currentStaff);
        Utilities.IntergratedProjectStaffApplication.changePassword.setVisible(true);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnAddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStaffActionPerformed
        if (Utilities.IntergratedProjectStaffApplication.addStaff != null) {
            Utilities.IntergratedProjectStaffApplication.addStaff.dispose();
        }
        Utilities.IntergratedProjectStaffApplication.addStaff = new AddStaff();
        Utilities.IntergratedProjectStaffApplication.addStaff.setVisible(true);
    }//GEN-LAST:event_btnAddStaffActionPerformed

    private void btnEmailStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmailStaffActionPerformed
        if (Utilities.IntergratedProjectStaffApplication.email != null) {
            Utilities.IntergratedProjectStaffApplication.email.dispose();
        }
        Utilities.IntergratedProjectStaffApplication.email = new EmailForm(currentStaff);
        Utilities.IntergratedProjectStaffApplication.email.setVisible(true);
    }//GEN-LAST:event_btnEmailStaffActionPerformed

    private void btnEmailAllStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmailAllStaffActionPerformed
        if (Utilities.IntergratedProjectStaffApplication.email != null) {
            Utilities.IntergratedProjectStaffApplication.email.dispose();
        }
        Utilities.IntergratedProjectStaffApplication.email = new EmailForm(originalStaff);
        Utilities.IntergratedProjectStaffApplication.email.setVisible(true);
    }//GEN-LAST:event_btnEmailAllStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEditStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEditStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEditStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEditStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEditStaff().setVisible(true);
            }
        });
    }
    
    public void formSetup() {        
        originalStaff = Utilities.IntergratedProjectStaffApplication.JSPConnector.getAllStaff();
        for (Staff staff : originalStaff) //copy arrayList
            searchedStaff.add(staff);        
        listLoad();
        lstStaff.setSelectedIndex(0);
        setCurrentStaffBoxs();        
        setEventListeners();
    }
    
    public void listLoad() {
        
        lstStaff.removeAll();
        
        lstStaffModel = new ArrayList<>();
                
        if (!searchedStaff.isEmpty()) {
            for (Staff staff : searchedStaff)
                lstStaffModel.add(staff.getFirstName() + " " + staff.getSurname());
        }
        lstStaff.setListData(lstStaffModel.toArray(new String[0])); //set list
    }
    
    public void setEventListeners() {
        lstStaff.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!searchActivated) //this check only allows the action to take place when manually changed,
                    setCurrentStaffBoxs(); // not when the list repopulates calling the listener
                else
                    searchActivated = false;
                currentSelection = lstStaff.getSelectedIndex();
            }
        });
    }
    
    public void setCurrentStaff() {
        currentStaff.setFirstName(txtFirstName.getText());
        currentStaff.setSurname(txtSurname.getText());
        currentStaff.setPhoneNo(txtPhoneNo.getText());
        currentStaff.setEmail(txtEmail.getText());
        if (cbManager.isSelected())
            currentStaff.setManager(1);
        else currentStaff.setManager(0);
    }
    
    public void setCurrentStaffBoxs() {
        //get current selected staff and set boxs
        currentStaff = searchedStaff.get(lstStaff.getSelectedIndex());
        txtFirstName.setText(currentStaff.getFirstName());
        txtSurname.setText(currentStaff.getSurname());
        txtPhoneNo.setText(currentStaff.getPhoneNo());
        txtEmail.setText(currentStaff.getEmail());
        if (currentStaff.getManager() == 1)
            cbManager.setSelected(true);
        else
            cbManager.setSelected(false);
    }
    
    public void clearTextBox() {
        txtFirstName.setText("");
        txtSurname.setText("");
        txtPhoneNo.setText("");
        txtEmail.setText("");
        cbManager.setSelected(false);
        txtSearchFirstName.setText("");
        txtSearchSurname.setText("");
        radBoth.setSelected(true);
    }
    
    public void addNewStaffList(Staff newStaff) {
        lstStaffModel.add(newStaff.getFirstName() + " " + newStaff.getSurname());
        searchedStaff.add(newStaff);
        originalStaff.add(newStaff);
        lstStaff.setListData(lstStaffModel.toArray(new String[0])); //set list
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStaff;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnEmailAllStaff;
    private javax.swing.JButton btnEmailStaff;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbManager;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JList<String> lstStaff;
    private javax.swing.JRadioButton radBoth;
    private javax.swing.JRadioButton radManagement;
    private javax.swing.JRadioButton radStaff;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtSearchFirstName;
    private javax.swing.JTextField txtSearchSurname;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
