package SupplierForms;

import Classes.Supplier;
import IngredientForms.ViewEditIngredients;
import Utilities.IntergratedProjectStaffApplication;
import UtilityForms.EmailForm;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class ViewEditSupplier extends javax.swing.JFrame {


    ArrayList<String> lstSupplierModel;
    ArrayList<Supplier> originalSupplier = new ArrayList<>();
    ArrayList<Supplier> searchedSupplier = new ArrayList<>();
    Supplier currentSupplier;
    Boolean searchActivated = false;
    int currentSelection = 0;
    
    public ViewEditSupplier() {
        initComponents();
        formSetup();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtAddress1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAddress2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPostcode = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPhoneNo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSupplier = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtSearchCity = new javax.swing.JTextField();
        txtSearchName = new javax.swing.JTextField();
        txtSearchPostcode = new javax.swing.JTextField();
        btnViewIngredients = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        btnEmailAll = new javax.swing.JButton();
        btnAddSupplier = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnEmail = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        jLabel1.setText("Name :");

        jLabel2.setText("Address Line 1 :");

        jLabel3.setText("Address Line 2 :");

        jLabel4.setText("City :");

        jLabel5.setText("PostCode :");

        jLabel6.setText("Phone No :");

        jLabel7.setText("Email :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("Name :");

        jLabel9.setText("Address Line 1 :");

        jLabel10.setText("Address Line 2 :");

        jLabel11.setText("City :");

        jLabel12.setText("Postcode :");

        jLabel13.setText("Phone No :");

        jLabel14.setText("Email :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Search Suppliers");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        lstSupplier.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstSupplier);

        jLabel17.setText("Name :");

        jLabel18.setText("City :");

        jLabel19.setText("Postcode :");

        btnViewIngredients.setText("View Ingredients");
        btnViewIngredients.setPreferredSize(new java.awt.Dimension(125, 40));
        btnViewIngredients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewIngredientsActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("Supplier Details");

        btnEmailAll.setText("Email All Suppliers");
        btnEmailAll.setMinimumSize(new java.awt.Dimension(60, 40));
        btnEmailAll.setPreferredSize(new java.awt.Dimension(75, 40));
        btnEmailAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmailAllActionPerformed(evt);
            }
        });

        btnAddSupplier.setText("Add Supplier");
        btnAddSupplier.setMinimumSize(new java.awt.Dimension(60, 40));
        btnAddSupplier.setPreferredSize(new java.awt.Dimension(100, 40));
        btnAddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupplierActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.setMinimumSize(new java.awt.Dimension(60, 40));
        btnClose.setPreferredSize(new java.awt.Dimension(75, 40));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnEmail.setText("Email Supplier");
        btnEmail.setPreferredSize(new java.awt.Dimension(125, 40));
        btnEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmailActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnConfirm.setText("Confirm");
        btnConfirm.setPreferredSize(new java.awt.Dimension(125, 40));
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove Supplier");
        btnRemove.setMinimumSize(new java.awt.Dimension(60, 40));
        btnRemove.setPreferredSize(new java.awt.Dimension(100, 40));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSearchPostcode))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtSearchCity, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName)
                                    .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(txtCity, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPostcode, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPhoneNo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAddress2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(btnAddSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnConfirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEmailAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnViewIngredients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(10, 10, 10))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtSearchPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtSearchCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnViewIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEmailAll, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplierActionPerformed
        if (Utilities.IntergratedProjectStaffApplication.addSupplier != null) {
            Utilities.IntergratedProjectStaffApplication.addSupplier.dispose();
        }
        Utilities.IntergratedProjectStaffApplication.addSupplier = new AddSupplier();
        Utilities.IntergratedProjectStaffApplication.addSupplier.setVisible(true);
    }//GEN-LAST:event_btnAddSupplierActionPerformed

    private void btnEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmailActionPerformed
        if (Utilities.IntergratedProjectStaffApplication.email != null) {
            Utilities.IntergratedProjectStaffApplication.email.dispose();
        }
        Utilities.IntergratedProjectStaffApplication.email = new EmailForm(currentSupplier);
        Utilities.IntergratedProjectStaffApplication.email.setVisible(true);
    }//GEN-LAST:event_btnEmailActionPerformed

    private void btnEmailAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmailAllActionPerformed
        if (Utilities.IntergratedProjectStaffApplication.email != null) {
            Utilities.IntergratedProjectStaffApplication.email.dispose();
        }
        Utilities.IntergratedProjectStaffApplication.email = new EmailForm(originalSupplier, 0);
        Utilities.IntergratedProjectStaffApplication.email.setVisible(true);
    }//GEN-LAST:event_btnEmailAllActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnViewIngredientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewIngredientsActionPerformed
        if (Utilities.IntergratedProjectStaffApplication.viewEditIngredient != null) {
            Utilities.IntergratedProjectStaffApplication.viewEditIngredient.dispose();
        }
        Utilities.IntergratedProjectStaffApplication.viewEditIngredient = new ViewEditIngredients(currentSupplier);
        Utilities.IntergratedProjectStaffApplication.viewEditIngredient.setVisible(true);
    }//GEN-LAST:event_btnViewIngredientsActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        boolean validation;
        
        validation = Utilities.Utilities.nullCheck(txtName, "Name", "Name") && Utilities.Utilities.alphbetic(txtName.getText(), "Name", "Name") &&
                Utilities.Utilities.nullCheck(txtAddress1, "Address 1", "Address 1") && Utilities.Utilities.alphanumeric(txtAddress1.getText(), "Address 1", "Address 1") &&
                Utilities.Utilities.nullCheck(txtAddress2, "Address 2", "Address 2") && Utilities.Utilities.alphanumeric(txtAddress2.getText(), "Address 2", "Address 2") &&
                Utilities.Utilities.nullCheck(txtCity, "City", "City") && Utilities.Utilities.alphbetic(txtCity.getText(), "City", "City") &&
                Utilities.Utilities.nullCheck(txtPostcode, "Postcode", "Postcode") && Utilities.Utilities.lengthCheckerGreater(txtPostcode, 7, "Postcode", "Postcode") &&
                Utilities.Utilities.lengthCheckerLess(txtPostcode, 8, "Postcode", "Postcode") &&
                Utilities.Utilities.phoneNoCheck(txtPhoneNo.getText()) &&
                Utilities.Utilities.nullCheck(txtEmail, "Email", "Email") && Utilities.Utilities.emailCheck(txtEmail);
        
        if (validation) {
            setCurrentSupplier();
            IntergratedProjectStaffApplication.JSPConnector.updateSupplier(currentSupplier);
            
            searchActivated = true;
            listLoad();
            lstSupplier.setSelectedIndex(currentSelection);
            
            Utilities.Utilities.infoBox("Supplier Updated : " + currentSupplier.getSupplierName(), "Supplier Updated");
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you wish to remove " + currentSupplier.getSupplierName() +
                "? Removing the supplier will remove all of their ingredients and any meal ingredients associated with them." ,"Remove Supplier", JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            
            IntergratedProjectStaffApplication.JSPConnector.deleteSupplier(currentSupplier);
            
            originalSupplier.remove(currentSupplier);
            searchedSupplier.remove(currentSupplier);
            
            searchActivated = true;
            listLoad();
            
            Utilities.Utilities.infoBox("Supplier removed : " + currentSupplier.getSupplierName(), "Supplier Removed");
            lstSupplier.setSelectedIndex(0);
            }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        searchActivated = true;
        searchedSupplier.clear();
        
        String name = txtSearchName.getText();
        String city = txtSearchCity.getText();
        String postcode = txtSearchPostcode.getText();
        
        for (Supplier supplier : originalSupplier) {
            if ((name.isEmpty() || name.equalsIgnoreCase(supplier.getSupplierName())) && (city.isEmpty() || city.equalsIgnoreCase(supplier.getCity())) &&
                    (postcode.isEmpty() || postcode.equalsIgnoreCase(supplier.getPostcode()))) {
                searchedSupplier.add(supplier);
            }
        }        
        
        if (searchedSupplier.isEmpty()) {
            for (Supplier supplier : originalSupplier) {
                searchedSupplier.add(supplier);
            }
            txtSearchName.setText("");
            txtSearchCity.setText("");
            txtSearchPostcode.setText("");
            Utilities.Utilities.infoBox("No matching results - Resetting List", "Search results");
        }
        
       listLoad();
       lstSupplier.setSelectedIndex(0);
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEditSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEditSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEditSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEditSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEditSupplier().setVisible(true);
            }
        });
    }
    
    public void formSetup() {        
        originalSupplier = Utilities.IntergratedProjectStaffApplication.JSPConnector.getAllSupplier();
        for (Supplier supplier : originalSupplier) //copy arrayList
            searchedSupplier.add(supplier);        
        listLoad();
        if (!searchedSupplier.isEmpty()) {
            lstSupplier.setSelectedIndex(0);
            setCurrentSupplierBoxs();
        }
        setEventListeners();
    }
    
    public void listLoad() {
        
        lstSupplier.removeAll();
        
        if (!searchedSupplier.isEmpty()) {
            lstSupplierModel = new ArrayList<>();        
            String[] supplierListArray;
            for (Supplier supplier : searchedSupplier) {
                lstSupplierModel.add(supplier.getSupplierName());
            }
            supplierListArray = lstSupplierModel.toArray(new String[0]);
            lstSupplier.setListData(supplierListArray); //set list    
        }
    }
    
    public void setEventListeners() {
        lstSupplier.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!searchActivated) //this check only allows the action to take place when manually changed,
                    setCurrentSupplierBoxs(); // not when the list repopulates calling the listener
                else
                    searchActivated = false;
                currentSelection = lstSupplier.getSelectedIndex();
            }
        });
    }
    
    public void setCurrentSupplier() {
        currentSupplier.setSupplierName(txtName.getText());
        currentSupplier.setAddress1(txtAddress1.getText());
        currentSupplier.setAddress2(txtAddress2.getText());
        currentSupplier.setCity(txtCity.getText());
        currentSupplier.setPostcode(txtPostcode.getText());
        currentSupplier.setPhoneNo(txtPhoneNo.getText());
        currentSupplier.setEmail(txtEmail.getText());
    }
    
    public void setCurrentSupplierBoxs() {
        //get current selected supplier and set boxs
        currentSupplier = searchedSupplier.get(lstSupplier.getSelectedIndex());
        txtName.setText(currentSupplier.getSupplierName());
        txtAddress1.setText(currentSupplier.getAddress1());
        txtAddress2.setText(currentSupplier.getAddress2());
        txtCity.setText(currentSupplier.getCity());
        txtPostcode.setText(currentSupplier.getPostcode());
        txtPhoneNo.setText(currentSupplier.getPhoneNo());
        txtEmail.setText(currentSupplier.getEmail());
    }
    
    public void clearTextBox() {
        txtSearchName.setText("");
        txtSearchCity.setText("");
        txtSearchPostcode.setText("");
        txtName.setText("");
        txtAddress1.setText("");
        txtAddress2.setText("");
        txtCity.setText("");
        txtPostcode.setText("");
        txtPhoneNo.setText("");
        txtEmail.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSupplier;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnEmail;
    private javax.swing.JButton btnEmailAll;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewIngredients;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JList<String> lstSupplier;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtPostcode;
    private javax.swing.JTextField txtSearchCity;
    private javax.swing.JTextField txtSearchName;
    private javax.swing.JTextField txtSearchPostcode;
    // End of variables declaration//GEN-END:variables
}
